### ISSUE TITLE
Players able to break locked objects

### ISSUE THREAD

**Issue by GottaSlay** [Brianetta/StickyLocks#15]
We just tested with my friends on my server and people are able to break each other's blocked objects. Chests and doors etc.

**Comment by Brianetta** [comment]
_This is intended behaviour._ You can break a chest or a door, but you cannot open it.

This plugin is intended to be used in conjunction with any other plugin that protects blocks from being broken. You can use GriefProtection claims, Towny plots, Factions claims, WorldGuard regions or any other plugin. This plugin is for controlling access, not for protecting against being broken. Having a lock make a door indestructible doesn't stop players breaking through the wall next to the door.

If you really want StickyLocks locked items to become indestructible to those who aren't on the access list, use my [StickyProtection](https://github.com/Brianetta/StickyProtection) plugin at the same time. I don't really maintain it, but I can't think of any reason why it shouldn't work since it's a very simple plugin that cancels the break event on any locked object where the player isn't also able to open it.

**Comment by Brianetta** [comment]
Actually, looking at it, its list of things that will break if the block they're sat on is broken is out of date, so I'll be needing to update that plugin.

**Comment by Brianetta** [comment]
You can give the new version of StickyProtection a bash if you don't have some other plugin to stop block breaking. It's been updated.
