### ISSUE TITLE
Shulker box support?

### ISSUE THREAD

**Issue by andrewamidei** [Brianetta/StickyLocks#17]
I see no way to use Sticky Locks with Shulker Boxes, are they supported? and if not, will there be support in the future?

**Comment by Brianetta** [comment]
You can protect Shulker Boxes, with one major caveat. **Your players will have to re-lock them every time they place one down**. This is why they're not protected by default - it's easier to explain to players that they're not protected, rather than explain why breaking the box breaks the lock.

You will have to add them to the list under **protectables:** in `config.yml`. You will need to add all seventeen variants, as shown below:

```yaml
- BLACK_SHULKER_BOX
- BLUE_SHULKER_BOX
- BROWN_SHULKER_BOX
- CYAN_SHULKER_BOX
- GRAY_SHULKER_BOX
- GREEN_SHULKER_BOX
- LIGHT_BLUE_SHULKER_BOX
- LIGHT_GRAY_SHULKER_BOX
- LIME_SHULKER_BOX
- MAGENTA_SHULKER_BOX
- ORANGE_SHULKER_BOX
- PINK_SHULKER_BOX
- PURPLE_SHULKER_BOX
- RED_SHULKER_BOX
- SHULKER_BOX
- WHITE_SHULKER_BOX
- YELLOW_SHULKER_BOX
```

**Comment by andrewamidei** [comment]
Thank you for a quick response. This brings up my second question, What about an auto-locking feature? I saw a YT video on Sticky Locks with an auto-lock feature in your config file. Was this removed or just not supported on shulkers?

**Comment by Brianetta** [comment]
Any player can enable autolock for themselves using `/sl autolock` in chat. It is no longer a global option. It will lock any protectable block that they place.

**Comment by andrewamidei** [comment]
Thank you very much, I really appreciate this plugin!
