### ISSUE TITLE
Locked items can be broken by other players

### ISSUE THREAD

**Issue by andrewamidei** [Brianetta/StickyLocks#18]
other players have been able to break locked chests to get items and break and replace items to unlock them.

**Comment by Brianetta** [comment]
StickyLocks prevents unauthorised players from opening locked items, but does **not** prevent them from breaking them. This is by design, to allow server administrators to separate locks from physical protection.

For example, a Factions PVP server might have areas where a faction's blocks cannot be broken, but where these areas can change as PVP battles take place. In this case, allowing the attackers to break open doors and chests as they become vulnerable is desirable.

If you want the locks on your doors and chests to also protect those doors and chests from an axe, you will need to install an additional plugin to accomplish this. I have published [a companion plugin](https://github.com/Brianetta/StickyProtection/) that can do this, but it's very simplistic. Ordinarily I would recommend that you protect blocks from destruction using plugins such as WorldGuard, GriefPrevention, Towny, Factions, UltimateClaims, etc.

**Comment by andrewamidei** [comment]
Ok, Thank you!
